package habiba.app.view;

import habiba.app.control.ActionAndFileHandling;
import habiba.app.control.InvoiceListener;
import habiba.app.model.InvoiceHeader;
import habiba.app.model.TableOfHeaders;
import habiba.app.model.InvoiceLine;
import habiba.app.model.TableOfItems;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;


public class Launcher extends javax.swing.JFrame {

    
    public Launcher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoicesTabelPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoicesTable = new javax.swing.JTable();
        deleteInvoiceButton = new javax.swing.JButton();
        createNewInvoiceButton = new javax.swing.JButton();
        createNewLineButton = new javax.swing.JButton();
        deleteLineButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        invoiceItemsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invTableOfItems = new javax.swing.JTable();
        invoiceHeaderPanel = new javax.swing.JPanel();
        invoiceNumerLabel = new javax.swing.JLabel();
        invoiceDateLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        invoiceTotalLabel = new javax.swing.JLabel();
        invNumLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        customerLabel = new javax.swing.JLabel();
        invTotalLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadFileMenuItem = new javax.swing.JMenuItem();
        saveFileMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Invoice Generator Desktop");
        setLocation(new java.awt.Point(250, 100));
        setSize(new java.awt.Dimension(1000, 550));

        invoicesTabelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Invoices Table"));

        invoicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Date", "Customer", "Total"
            }
        ));
        invoicesTable.getSelectionModel().addListSelectionListener(invListener);
        jScrollPane1.setViewportView(invoicesTable);

        javax.swing.GroupLayout invoicesTabelPanelLayout = new javax.swing.GroupLayout(invoicesTabelPanel);
        invoicesTabelPanel.setLayout(invoicesTabelPanelLayout);
        invoicesTabelPanelLayout.setHorizontalGroup(
            invoicesTabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoicesTabelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        invoicesTabelPanelLayout.setVerticalGroup(
            invoicesTabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicesTabelPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        deleteInvoiceButton.setText("Delete Invoice");
        deleteInvoiceButton.addActionListener(actionListener);

        createNewInvoiceButton.setText("Create New Invoice");
        createNewInvoiceButton.addActionListener(actionListener);

        createNewLineButton.setText("Create New Line");
        createNewLineButton.addActionListener(actionListener);

        deleteLineButton.setText("Delete Line");
        deleteLineButton.addActionListener(actionListener);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Invoice Inspector", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        invoiceItemsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Invoice Items"));

        invTableOfItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Item Name", "Item Price", "Count", "Item Total"
            }
        ));
        jScrollPane2.setViewportView(invTableOfItems);

        javax.swing.GroupLayout invoiceItemsPanelLayout = new javax.swing.GroupLayout(invoiceItemsPanel);
        invoiceItemsPanel.setLayout(invoiceItemsPanelLayout);
        invoiceItemsPanelLayout.setHorizontalGroup(
            invoiceItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
            .addGroup(invoiceItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(invoiceItemsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        invoiceItemsPanelLayout.setVerticalGroup(
            invoiceItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
            .addGroup(invoiceItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(invoiceItemsPanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        invoiceNumerLabel.setText("Invoice Number");

        invoiceDateLabel.setText("Invoice Date");

        customerNameLabel.setText("Customer Name");

        invoiceTotalLabel.setText("Invoice Total");

        javax.swing.GroupLayout invoiceHeaderPanelLayout = new javax.swing.GroupLayout(invoiceHeaderPanel);
        invoiceHeaderPanel.setLayout(invoiceHeaderPanelLayout);
        invoiceHeaderPanelLayout.setHorizontalGroup(
            invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceHeaderPanelLayout.createSequentialGroup()
                .addGroup(invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(invoiceHeaderPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(invoiceNumerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(invoiceDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(customerNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(invoiceTotalLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceHeaderPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(invoiceHeaderPanelLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(invNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceHeaderPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(customerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(invTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        invoiceHeaderPanelLayout.setVerticalGroup(
            invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(invoiceHeaderPanelLayout.createSequentialGroup()
                        .addGroup(invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invNumLabel)
                            .addComponent(invoiceNumerLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLabel)
                            .addComponent(invoiceDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(invoiceHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerLabel)
                            .addComponent(customerNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invTotalLabel))
                    .addGroup(invoiceHeaderPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(invoiceTotalLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(invoiceHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(invoiceItemsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(invoiceHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(invoiceItemsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        fileMenu.setText("File");

        loadFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        loadFileMenuItem.setText("Load File");
        loadFileMenuItem.addActionListener(actionListener);
        fileMenu.add(loadFileMenuItem);

        saveFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveFileMenuItem.setText("Save File");
        saveFileMenuItem.addActionListener(actionListener);
        fileMenu.add(saveFileMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(createNewInvoiceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteInvoiceButton)
                        .addGap(301, 301, 301)
                        .addComponent(createNewLineButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteLineButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(invoicesTabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(invoicesTabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewInvoiceButton)
                    .addComponent(createNewLineButton)
                    .addComponent(deleteLineButton)
                    .addComponent(deleteInvoiceButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Launcher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewInvoiceButton;
    private javax.swing.JButton createNewLineButton;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteInvoiceButton;
    private javax.swing.JButton deleteLineButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel invNumLabel;
    private javax.swing.JTable invTableOfItems;
    private javax.swing.JLabel invTotalLabel;
    private javax.swing.JLabel invoiceDateLabel;
    private javax.swing.JPanel invoiceHeaderPanel;
    private javax.swing.JPanel invoiceItemsPanel;
    private javax.swing.JLabel invoiceNumerLabel;
    private javax.swing.JLabel invoiceTotalLabel;
    private javax.swing.JPanel invoicesTabelPanel;
    private javax.swing.JTable invoicesTable;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadFileMenuItem;
    private javax.swing.JMenuItem saveFileMenuItem;
    // End of variables declaration//GEN-END:variables
    
    
    private ArrayList<InvoiceLine> items;
    private TableOfHeaders tableOfHeaders = new TableOfHeaders();
    private ActionAndFileHandling actionListener = new ActionAndFileHandling(this);
    private final InvoiceListener invListener = new InvoiceListener(this);
    private ArrayList<InvoiceHeader> headers;
    private TableOfItems tableOfItems = new TableOfItems();
    NewInvoiceWizard InvWiz = new NewInvoiceWizard(this);
    NewLineWizard lineWiz = new NewLineWizard(this);

    public ActionAndFileHandling getActionsListener() {
        return actionListener;
    }

    public ArrayList<InvoiceLine> getItems() {
        return items;
    }

    public void setItems(ArrayList<InvoiceLine> itemsArrayList) {
        this.items = itemsArrayList;
    }

    public void setActionListener(ActionAndFileHandling actionListener) {
        this.actionListener = actionListener;
    }
    
    public void setHeaders(ArrayList<InvoiceHeader> headers) {
        this.headers = headers;
    }

    public ArrayList<InvoiceHeader> getHeaders() {
        return headers;
    }
    
    public InvoiceHeader getNum(int number){
        for (InvoiceHeader header : headers){
            if (header.getInvNum() == number) {
                return header;
            }
        }
        return null;
    }

    public void setHeaderTable(TableOfHeaders headerTable) {
        this.tableOfHeaders = headerTable;
    }

    public TableOfHeaders getTableOfHeader() {
        return tableOfHeaders;
        
    }
        public JTable getInvoicesData() {
        return invoicesTable;
    }

    public void setInvoicesTable(JTable invoicesTable) {
        this.invoicesTable = invoicesTable;
    }


    public TableOfItems getItemsTable() {
        return tableOfItems;
    }

    
        public JLabel getNameLabel() {
        return customerLabel;
    }
        
    public void setItemsTable(TableOfItems itemsTable) {
        this.tableOfItems = itemsTable;
    }
    


    public void setCustomerNameValueLabel(JLabel customerLabel) {
        this.customerLabel = customerLabel;
    }

        public void setDateLabel(JLabel dateLabel) {
        this.dateLabel = dateLabel;
    }
    
    public JLabel getDateLabel() {
        return dateLabel;
    }



    public JLabel getInvoiceLabel() {
        return invNumLabel;
    }

    public void setNumerLabel(JLabel label) {
        this.invNumLabel = label;
    }

    public JLabel getTotalLabel() {
        return invTotalLabel;
    }
    
        public void setTableOfItems(JTable tableOfItems) {
        this.invTableOfItems = tableOfItems;
    }
    
    public NewInvoiceWizard getInvWiz() {
        return InvWiz;
    }

    public void setInvWiz(NewInvoiceWizard invWiz) {
        this.InvWiz = invWiz;
    }
    
    public NewLineWizard getNewLineWiz() {
        return lineWiz;
    }
        public JTable getInvoiceItems() {
        return invTableOfItems;
    }

    public void setNewLineWiz(NewLineWizard newLineWiz) {
        this.lineWiz = newLineWiz;
    }

    public void setTotalLabel(JLabel totalLabel) {
        this.invTotalLabel = totalLabel;
    }





}
